// Copyright 2025, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import { WshClient } from "./wshclient";

// WshServerCommandToDeclMap
class RpcApiType {
    // command "activity" [call]
    ActivityCommand(client: WshClient, data: ActivityUpdate, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("activity", data, opts);
    }

    // command "aisendmessage" [call]
    AiSendMessageCommand(client: WshClient, data: AiMessageData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("aisendmessage", data, opts);
    }

    // command "authenticate" [call]
    AuthenticateCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        return client.wshRpcCall("authenticate", data, opts);
    }

    // command "authenticatetoken" [call]
    AuthenticateTokenCommand(client: WshClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        return client.wshRpcCall("authenticatetoken", data, opts);
    }

    // command "authenticatetokenverify" [call]
    AuthenticateTokenVerifyCommand(client: WshClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        return client.wshRpcCall("authenticatetokenverify", data, opts);
    }

    // command "blockinfo" [call]
    BlockInfoCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<BlockInfoData> {
        return client.wshRpcCall("blockinfo", data, opts);
    }

    // command "blockslist" [call]
    BlocksListCommand(client: WshClient, data: BlocksListRequest, opts?: RpcOpts): Promise<BlocksListEntry[]> {
        return client.wshRpcCall("blockslist", data, opts);
    }

    // command "captureblockscreenshot" [call]
    CaptureBlockScreenshotCommand(client: WshClient, data: CommandCaptureBlockScreenshotData, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("captureblockscreenshot", data, opts);
    }

    // command "checkgoversion" [call]
    CheckGoVersionCommand(client: WshClient, opts?: RpcOpts): Promise<CommandCheckGoVersionRtnData> {
        return client.wshRpcCall("checkgoversion", null, opts);
    }

    // command "connconnect" [call]
    ConnConnectCommand(client: WshClient, data: ConnRequest, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("connconnect", data, opts);
    }

    // command "conndisconnect" [call]
    ConnDisconnectCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("conndisconnect", data, opts);
    }

    // command "connensure" [call]
    ConnEnsureCommand(client: WshClient, data: ConnExtData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("connensure", data, opts);
    }

    // command "connlist" [call]
    ConnListCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        return client.wshRpcCall("connlist", null, opts);
    }

    // command "connlistaws" [call]
    ConnListAWSCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        return client.wshRpcCall("connlistaws", null, opts);
    }

    // command "connreinstallwsh" [call]
    ConnReinstallWshCommand(client: WshClient, data: ConnExtData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("connreinstallwsh", data, opts);
    }

    // command "connstatus" [call]
    ConnStatusCommand(client: WshClient, opts?: RpcOpts): Promise<ConnStatus[]> {
        return client.wshRpcCall("connstatus", null, opts);
    }

    // command "connupdatewsh" [call]
    ConnUpdateWshCommand(client: WshClient, data: RemoteInfo, opts?: RpcOpts): Promise<boolean> {
        return client.wshRpcCall("connupdatewsh", data, opts);
    }

    // command "controllerappendoutput" [call]
    ControllerAppendOutputCommand(client: WshClient, data: CommandControllerAppendOutputData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("controllerappendoutput", data, opts);
    }

    // command "controllerinput" [call]
    ControllerInputCommand(client: WshClient, data: CommandBlockInputData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("controllerinput", data, opts);
    }

    // command "controllerresync" [call]
    ControllerResyncCommand(client: WshClient, data: CommandControllerResyncData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("controllerresync", data, opts);
    }

    // command "controllerstop" [call]
    ControllerStopCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("controllerstop", data, opts);
    }

    // command "createblock" [call]
    CreateBlockCommand(client: WshClient, data: CommandCreateBlockData, opts?: RpcOpts): Promise<ORef> {
        return client.wshRpcCall("createblock", data, opts);
    }

    // command "createsubblock" [call]
    CreateSubBlockCommand(client: WshClient, data: CommandCreateSubBlockData, opts?: RpcOpts): Promise<ORef> {
        return client.wshRpcCall("createsubblock", data, opts);
    }

    // command "cwconfigget" [call]
    CWConfigGetCommand(client: WshClient, opts?: RpcOpts): Promise<CWConfigType> {
        return client.wshRpcCall("cwconfigget", null, opts);
    }

    // command "cwconfiggetproject" [call]
    CWConfigGetProjectCommand(client: WshClient, data: CommandCWConfigGetProjectData, opts?: RpcOpts): Promise<CWConfigType> {
        return client.wshRpcCall("cwconfiggetproject", data, opts);
    }

    // command "cwconfigset" [call]
    CWConfigSetCommand(client: WshClient, data: CommandCWConfigSetData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("cwconfigset", data, opts);
    }

    // command "cwsessionstatus" [call]
    CWSessionStatusCommand(client: WshClient, data: CommandCWSessionStatusData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("cwsessionstatus", data, opts);
    }

    // command "decisionfiltercalculatescore" [call]
    DecisionFilterCalculateScoreCommand(client: WshClient, data: CommandDecisionFilterCalculateScoreData, opts?: RpcOpts): Promise<DecisionFilterScoreResultData> {
        return client.wshRpcCall("decisionfiltercalculatescore", data, opts);
    }

    // command "decisionfilterexport" [call]
    DecisionFilterExportCommand(client: WshClient, data: CommandDecisionFilterExportData, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("decisionfilterexport", data, opts);
    }

    // command "decisionfiltergetrubric" [call]
    DecisionFilterGetRubricCommand(client: WshClient, data: CommandDecisionFilterGetRubricData, opts?: RpcOpts): Promise<DecisionFilterRubricData> {
        return client.wshRpcCall("decisionfiltergetrubric", data, opts);
    }

    // command "decisionfilterlist" [call]
    DecisionFilterListCommand(client: WshClient, data: CommandDecisionFilterListData, opts?: RpcOpts): Promise<DecisionFilterResponseData[]> {
        return client.wshRpcCall("decisionfilterlist", data, opts);
    }

    // command "decisionfilterload" [call]
    DecisionFilterLoadCommand(client: WshClient, data: CommandDecisionFilterLoadData, opts?: RpcOpts): Promise<DecisionFilterResponseData> {
        return client.wshRpcCall("decisionfilterload", data, opts);
    }

    // command "decisionfilterreadfile" [call]
    DecisionFilterReadFileCommand(client: WshClient, data: CommandDecisionFilterReadFileData, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("decisionfilterreadfile", data, opts);
    }

    // command "decisionfiltersave" [call]
    DecisionFilterSaveCommand(client: WshClient, data: CommandDecisionFilterSaveData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("decisionfiltersave", data, opts);
    }

    // command "deleteappfile" [call]
    DeleteAppFileCommand(client: WshClient, data: CommandDeleteAppFileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("deleteappfile", data, opts);
    }

    // command "deleteblock" [call]
    DeleteBlockCommand(client: WshClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("deleteblock", data, opts);
    }

    // command "deletebuilder" [call]
    DeleteBuilderCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("deletebuilder", data, opts);
    }

    // command "deletesubblock" [call]
    DeleteSubBlockCommand(client: WshClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("deletesubblock", data, opts);
    }

    // command "dismisswshfail" [call]
    DismissWshFailCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("dismisswshfail", data, opts);
    }

    // command "dispose" [call]
    DisposeCommand(client: WshClient, data: CommandDisposeData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("dispose", data, opts);
    }

    // command "disposesuggestions" [call]
    DisposeSuggestionsCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("disposesuggestions", data, opts);
    }

    // command "electrondecrypt" [call]
    ElectronDecryptCommand(client: WshClient, data: CommandElectronDecryptData, opts?: RpcOpts): Promise<CommandElectronDecryptRtnData> {
        return client.wshRpcCall("electrondecrypt", data, opts);
    }

    // command "electronencrypt" [call]
    ElectronEncryptCommand(client: WshClient, data: CommandElectronEncryptData, opts?: RpcOpts): Promise<CommandElectronEncryptRtnData> {
        return client.wshRpcCall("electronencrypt", data, opts);
    }

    // command "eventpublish" [call]
    EventPublishCommand(client: WshClient, data: WaveEvent, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("eventpublish", data, opts);
    }

    // command "eventreadhistory" [call]
    EventReadHistoryCommand(client: WshClient, data: CommandEventReadHistoryData, opts?: RpcOpts): Promise<WaveEvent[]> {
        return client.wshRpcCall("eventreadhistory", data, opts);
    }

    // command "eventrecv" [call]
    EventRecvCommand(client: WshClient, data: WaveEvent, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("eventrecv", data, opts);
    }

    // command "eventsub" [call]
    EventSubCommand(client: WshClient, data: SubscriptionRequest, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("eventsub", data, opts);
    }

    // command "eventunsub" [call]
    EventUnsubCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("eventunsub", data, opts);
    }

    // command "eventunsuball" [call]
    EventUnsubAllCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("eventunsuball", null, opts);
    }

    // command "fetchsuggestions" [call]
    FetchSuggestionsCommand(client: WshClient, data: FetchSuggestionsData, opts?: RpcOpts): Promise<FetchSuggestionsResponse> {
        return client.wshRpcCall("fetchsuggestions", data, opts);
    }

    // command "fileappend" [call]
    FileAppendCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("fileappend", data, opts);
    }

    // command "fileappendijson" [call]
    FileAppendIJsonCommand(client: WshClient, data: CommandAppendIJsonData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("fileappendijson", data, opts);
    }

    // command "filecopy" [call]
    FileCopyCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("filecopy", data, opts);
    }

    // command "filecreate" [call]
    FileCreateCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("filecreate", data, opts);
    }

    // command "filedelete" [call]
    FileDeleteCommand(client: WshClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("filedelete", data, opts);
    }

    // command "fileinfo" [call]
    FileInfoCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<FileInfo> {
        return client.wshRpcCall("fileinfo", data, opts);
    }

    // command "filejoin" [call]
    FileJoinCommand(client: WshClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        return client.wshRpcCall("filejoin", data, opts);
    }

    // command "filelist" [call]
    FileListCommand(client: WshClient, data: FileListData, opts?: RpcOpts): Promise<FileInfo[]> {
        return client.wshRpcCall("filelist", data, opts);
    }

    // command "fileliststream" [responsestream]
	FileListStreamCommand(client: WshClient, data: FileListData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        return client.wshRpcStream("fileliststream", data, opts);
    }

    // command "filemkdir" [call]
    FileMkdirCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("filemkdir", data, opts);
    }

    // command "filemove" [call]
    FileMoveCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("filemove", data, opts);
    }

    // command "fileread" [call]
    FileReadCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<FileData> {
        return client.wshRpcCall("fileread", data, opts);
    }

    // command "filereadstream" [responsestream]
	FileReadStreamCommand(client: WshClient, data: FileData, opts?: RpcOpts): AsyncGenerator<FileData, void, boolean> {
        return client.wshRpcStream("filereadstream", data, opts);
    }

    // command "filerestorebackup" [call]
    FileRestoreBackupCommand(client: WshClient, data: CommandFileRestoreBackupData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("filerestorebackup", data, opts);
    }

    // command "filesharecapability" [call]
    FileShareCapabilityCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<FileShareCapability> {
        return client.wshRpcCall("filesharecapability", data, opts);
    }

    // command "filestreamtar" [responsestream]
	FileStreamTarCommand(client: WshClient, data: CommandRemoteStreamTarData, opts?: RpcOpts): AsyncGenerator<Packet, void, boolean> {
        return client.wshRpcStream("filestreamtar", data, opts);
    }

    // command "filewrite" [call]
    FileWriteCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("filewrite", data, opts);
    }

    // command "findgitbash" [call]
    FindGitBashCommand(client: WshClient, data: boolean, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("findgitbash", data, opts);
    }

    // command "focuswindow" [call]
    FocusWindowCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("focuswindow", data, opts);
    }

    // command "getbuilderoutput" [call]
    GetBuilderOutputCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<string[]> {
        return client.wshRpcCall("getbuilderoutput", data, opts);
    }

    // command "getbuilderstatus" [call]
    GetBuilderStatusCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<BuilderStatusData> {
        return client.wshRpcCall("getbuilderstatus", data, opts);
    }

    // command "getfullconfig" [call]
    GetFullConfigCommand(client: WshClient, opts?: RpcOpts): Promise<FullConfigType> {
        return client.wshRpcCall("getfullconfig", null, opts);
    }

    // command "getjwtpublickey" [call]
    GetJwtPublicKeyCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("getjwtpublickey", null, opts);
    }

    // command "getmeta" [call]
    GetMetaCommand(client: WshClient, data: CommandGetMetaData, opts?: RpcOpts): Promise<MetaType> {
        return client.wshRpcCall("getmeta", data, opts);
    }

    // command "getrtinfo" [call]
    GetRTInfoCommand(client: WshClient, data: CommandGetRTInfoData, opts?: RpcOpts): Promise<ObjRTInfo> {
        return client.wshRpcCall("getrtinfo", data, opts);
    }

    // command "getsecrets" [call]
    GetSecretsCommand(client: WshClient, data: string[], opts?: RpcOpts): Promise<{[key: string]: string}> {
        return client.wshRpcCall("getsecrets", data, opts);
    }

    // command "getsecretslinuxstoragebackend" [call]
    GetSecretsLinuxStorageBackendCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("getsecretslinuxstoragebackend", null, opts);
    }

    // command "getsecretsnames" [call]
    GetSecretsNamesCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        return client.wshRpcCall("getsecretsnames", null, opts);
    }

    // command "gettab" [call]
    GetTabCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<Tab> {
        return client.wshRpcCall("gettab", data, opts);
    }

    // command "gettempdir" [call]
    GetTempDirCommand(client: WshClient, data: CommandGetTempDirData, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("gettempdir", data, opts);
    }

    // command "getupdatechannel" [call]
    GetUpdateChannelCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("getupdatechannel", null, opts);
    }

    // command "getvar" [call]
    GetVarCommand(client: WshClient, data: CommandVarData, opts?: RpcOpts): Promise<CommandVarResponseData> {
        return client.wshRpcCall("getvar", data, opts);
    }

    // command "getwaveaichat" [call]
    GetWaveAIChatCommand(client: WshClient, data: CommandGetWaveAIChatData, opts?: RpcOpts): Promise<UIChat> {
        return client.wshRpcCall("getwaveaichat", data, opts);
    }

    // command "getwaveaimodeconfig" [call]
    GetWaveAIModeConfigCommand(client: WshClient, opts?: RpcOpts): Promise<AIModeConfigUpdate> {
        return client.wshRpcCall("getwaveaimodeconfig", null, opts);
    }

    // command "getwaveairatelimit" [call]
    GetWaveAIRateLimitCommand(client: WshClient, opts?: RpcOpts): Promise<RateLimitInfo> {
        return client.wshRpcCall("getwaveairatelimit", null, opts);
    }

    // command "gitdirectorystatus" [call]
    GitDirectoryStatusCommand(client: WshClient, data: CommandGitDirectoryStatusData, opts?: RpcOpts): Promise<GitDirectoryStatusData> {
        return client.wshRpcCall("gitdirectorystatus", data, opts);
    }

    // command "gitfilediff" [call]
    GitFileDiffCommand(client: WshClient, data: CommandGitFileDiffData, opts?: RpcOpts): Promise<GitFileDiffData> {
        return client.wshRpcCall("gitfilediff", data, opts);
    }

    // command "githubauth" [call]
    GitHubAuthCommand(client: WshClient, data: CommandGitHubAuthData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("githubauth", data, opts);
    }

    // command "githubauthstatus" [call]
    GitHubAuthStatusCommand(client: WshClient, opts?: RpcOpts): Promise<GitHubAuthStatusData> {
        return client.wshRpcCall("githubauthstatus", null, opts);
    }

    // command "githubcreatepr" [call]
    GitHubCreatePRCommand(client: WshClient, data: CommandGitHubPRCreateData, opts?: RpcOpts): Promise<GitHubPRResponseData> {
        return client.wshRpcCall("githubcreatepr", data, opts);
    }

    // command "githubgetpr" [call]
    GitHubGetPRCommand(client: WshClient, data: CommandGitHubGetPRData, opts?: RpcOpts): Promise<GitHubPRStatusData> {
        return client.wshRpcCall("githubgetpr", data, opts);
    }

    // command "githubgetprbybranch" [call]
    GitHubGetPRByBranchCommand(client: WshClient, data: CommandGitHubGetPRByBranchData, opts?: RpcOpts): Promise<GitHubPRStatusData> {
        return client.wshRpcCall("githubgetprbybranch", data, opts);
    }

    // command "githubmergepr" [call]
    GitHubMergePRCommand(client: WshClient, data: CommandGitHubMergePRData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("githubmergepr", data, opts);
    }

    // command "gitpushbranch" [call]
    GitPushBranchCommand(client: WshClient, data: CommandGitPushBranchData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("gitpushbranch", data, opts);
    }

    // command "gitstageall" [call]
    GitStageAllCommand(client: WshClient, data: CommandGitStageAllData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("gitstageall", data, opts);
    }

    // command "gitstagefile" [call]
    GitStageFileCommand(client: WshClient, data: CommandGitStageFileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("gitstagefile", data, opts);
    }

    // command "gitunstageall" [call]
    GitUnstageAllCommand(client: WshClient, data: CommandGitStageAllData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("gitunstageall", data, opts);
    }

    // command "gitunstagefile" [call]
    GitUnstageFileCommand(client: WshClient, data: CommandGitStageFileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("gitunstagefile", data, opts);
    }

    // command "listallappfiles" [call]
    ListAllAppFilesCommand(client: WshClient, data: CommandListAllAppFilesData, opts?: RpcOpts): Promise<CommandListAllAppFilesRtnData> {
        return client.wshRpcCall("listallappfiles", data, opts);
    }

    // command "listallapps" [call]
    ListAllAppsCommand(client: WshClient, opts?: RpcOpts): Promise<AppInfo[]> {
        return client.wshRpcCall("listallapps", null, opts);
    }

    // command "listalleditableapps" [call]
    ListAllEditableAppsCommand(client: WshClient, opts?: RpcOpts): Promise<AppInfo[]> {
        return client.wshRpcCall("listalleditableapps", null, opts);
    }

    // command "makedraftfromlocal" [call]
    MakeDraftFromLocalCommand(client: WshClient, data: CommandMakeDraftFromLocalData, opts?: RpcOpts): Promise<CommandMakeDraftFromLocalRtnData> {
        return client.wshRpcCall("makedraftfromlocal", data, opts);
    }

    // command "mcpaddserver" [call]
    MCPAddServerCommand(client: WshClient, data: CommandMCPAddServerData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("mcpaddserver", data, opts);
    }

    // command "mcpgetstatus" [call]
    MCPGetStatusCommand(client: WshClient, data: CommandMCPGetStatusData, opts?: RpcOpts): Promise<MCPServerStatusData> {
        return client.wshRpcCall("mcpgetstatus", data, opts);
    }

    // command "mcplistservers" [call]
    MCPListServersCommand(client: WshClient, data: CommandMCPListServersData, opts?: RpcOpts): Promise<MCPServerData[]> {
        return client.wshRpcCall("mcplistservers", data, opts);
    }

    // command "mcplisttemplates" [call]
    MCPListTemplatesCommand(client: WshClient, opts?: RpcOpts): Promise<MCPTemplateData[]> {
        return client.wshRpcCall("mcplisttemplates", null, opts);
    }

    // command "mcpremoveserver" [call]
    MCPRemoveServerCommand(client: WshClient, data: CommandMCPRemoveServerData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("mcpremoveserver", data, opts);
    }

    // command "mcptestconnection" [call]
    MCPTestConnectionCommand(client: WshClient, data: CommandMCPTestConnectionData, opts?: RpcOpts): Promise<MCPServerStatusData> {
        return client.wshRpcCall("mcptestconnection", data, opts);
    }

    // command "mcpupdateserver" [call]
    MCPUpdateServerCommand(client: WshClient, data: CommandMCPUpdateServerData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("mcpupdateserver", data, opts);
    }

    // command "message" [call]
    MessageCommand(client: WshClient, data: CommandMessageData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("message", data, opts);
    }

    // command "networkonline" [call]
    NetworkOnlineCommand(client: WshClient, opts?: RpcOpts): Promise<boolean> {
        return client.wshRpcCall("networkonline", null, opts);
    }

    // command "notify" [call]
    NotifyCommand(client: WshClient, data: WaveNotificationOptions, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("notify", data, opts);
    }

    // command "path" [call]
    PathCommand(client: WshClient, data: PathCommandData, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("path", data, opts);
    }

    // command "platformlink" [call]
    PlatformLinkCommand(client: WshClient, data: CommandPlatformLinkData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("platformlink", data, opts);
    }

    // command "platformprds" [call]
    PlatformPRDsCommand(client: WshClient, data: CommandPlatformPRDsData, opts?: RpcOpts): Promise<PlatformPRDsData> {
        return client.wshRpcCall("platformprds", data, opts);
    }

    // command "platformproducts" [call]
    PlatformProductsCommand(client: WshClient, data: CommandPlatformProductsData, opts?: RpcOpts): Promise<PlatformProductsData> {
        return client.wshRpcCall("platformproducts", data, opts);
    }

    // command "platformprojects" [call]
    PlatformProjectsCommand(client: WshClient, data: CommandPlatformProjectsData, opts?: RpcOpts): Promise<PlatformProjectsData> {
        return client.wshRpcCall("platformprojects", data, opts);
    }

    // command "platformspecs" [call]
    PlatformSpecsCommand(client: WshClient, data: CommandPlatformSpecsData, opts?: RpcOpts): Promise<PlatformSpecsData> {
        return client.wshRpcCall("platformspecs", data, opts);
    }

    // command "platformstatus" [call]
    PlatformStatusCommand(client: WshClient, opts?: RpcOpts): Promise<PlatformStatusData> {
        return client.wshRpcCall("platformstatus", null, opts);
    }

    // command "platformtaskdetail" [call]
    PlatformTaskDetailCommand(client: WshClient, data: CommandPlatformTaskDetailData, opts?: RpcOpts): Promise<PlatformTaskDetailData> {
        return client.wshRpcCall("platformtaskdetail", data, opts);
    }

    // command "platformtasks" [call]
    PlatformTasksCommand(client: WshClient, data: CommandPlatformTasksData, opts?: RpcOpts): Promise<PlatformTasksData> {
        return client.wshRpcCall("platformtasks", data, opts);
    }

    // command "platformteams" [call]
    PlatformTeamsCommand(client: WshClient, opts?: RpcOpts): Promise<PlatformTeamsData> {
        return client.wshRpcCall("platformteams", null, opts);
    }

    // command "platformunlink" [call]
    PlatformUnlinkCommand(client: WshClient, data: CommandPlatformUnlinkData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("platformunlink", data, opts);
    }

    // command "platformupdatestatus" [call]
    PlatformUpdateStatusCommand(client: WshClient, data: CommandPlatformUpdateStatusData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("platformupdatestatus", data, opts);
    }

    // command "pluginconfigure" [call]
    PluginConfigureCommand(client: WshClient, data: CommandPluginConfigureData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("pluginconfigure", data, opts);
    }

    // command "plugindisable" [call]
    PluginDisableCommand(client: WshClient, data: CommandPluginDisableData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("plugindisable", data, opts);
    }

    // command "pluginenable" [call]
    PluginEnableCommand(client: WshClient, data: CommandPluginEnableData, opts?: RpcOpts): Promise<InstalledPluginData> {
        return client.wshRpcCall("pluginenable", data, opts);
    }

    // command "plugingetcategories" [call]
    PluginGetCategoriesCommand(client: WshClient, opts?: RpcOpts): Promise<PluginCategoryData[]> {
        return client.wshRpcCall("plugingetcategories", null, opts);
    }

    // command "pluginlistavailable" [call]
    PluginListAvailableCommand(client: WshClient, opts?: RpcOpts): Promise<PluginData[]> {
        return client.wshRpcCall("pluginlistavailable", null, opts);
    }

    // command "pluginlistinstalled" [call]
    PluginListInstalledCommand(client: WshClient, data: CommandPluginListData, opts?: RpcOpts): Promise<InstalledPluginData[]> {
        return client.wshRpcCall("pluginlistinstalled", data, opts);
    }

    // command "processmetrics" [call]
    ProcessMetricsCommand(client: WshClient, data: CommandProcessMetricsData, opts?: RpcOpts): Promise<ProcessMetricsData> {
        return client.wshRpcCall("processmetrics", data, opts);
    }

    // command "processmetricsbatch" [call]
    ProcessMetricsBatchCommand(client: WshClient, data: CommandProcessMetricsBatchData, opts?: RpcOpts): Promise<{[key: string]: ProcessMetricsData}> {
        return client.wshRpcCall("processmetricsbatch", data, opts);
    }

    // command "publishapp" [call]
    PublishAppCommand(client: WshClient, data: CommandPublishAppData, opts?: RpcOpts): Promise<CommandPublishAppRtnData> {
        return client.wshRpcCall("publishapp", data, opts);
    }

    // command "readappfile" [call]
    ReadAppFileCommand(client: WshClient, data: CommandReadAppFileData, opts?: RpcOpts): Promise<CommandReadAppFileRtnData> {
        return client.wshRpcCall("readappfile", data, opts);
    }

    // command "recordtevent" [call]
    RecordTEventCommand(client: WshClient, data: TEvent, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("recordtevent", data, opts);
    }

    // command "remotefilecopy" [call]
    RemoteFileCopyCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<boolean> {
        return client.wshRpcCall("remotefilecopy", data, opts);
    }

    // command "remotefiledelete" [call]
    RemoteFileDeleteCommand(client: WshClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("remotefiledelete", data, opts);
    }

    // command "remotefileinfo" [call]
    RemoteFileInfoCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<FileInfo> {
        return client.wshRpcCall("remotefileinfo", data, opts);
    }

    // command "remotefilejoin" [call]
    RemoteFileJoinCommand(client: WshClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        return client.wshRpcCall("remotefilejoin", data, opts);
    }

    // command "remotefilemove" [call]
    RemoteFileMoveCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("remotefilemove", data, opts);
    }

    // command "remotefiletouch" [call]
    RemoteFileTouchCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("remotefiletouch", data, opts);
    }

    // command "remotegetinfo" [call]
    RemoteGetInfoCommand(client: WshClient, opts?: RpcOpts): Promise<RemoteInfo> {
        return client.wshRpcCall("remotegetinfo", null, opts);
    }

    // command "remoteinstallrcfiles" [call]
    RemoteInstallRcFilesCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("remoteinstallrcfiles", null, opts);
    }

    // command "remotelistentries" [responsestream]
	RemoteListEntriesCommand(client: WshClient, data: CommandRemoteListEntriesData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        return client.wshRpcStream("remotelistentries", data, opts);
    }

    // command "remotemkdir" [call]
    RemoteMkdirCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("remotemkdir", data, opts);
    }

    // command "remotestreamcpudata" [responsestream]
	RemoteStreamCpuDataCommand(client: WshClient, opts?: RpcOpts): AsyncGenerator<TimeSeriesData, void, boolean> {
        return client.wshRpcStream("remotestreamcpudata", null, opts);
    }

    // command "remotestreamfile" [responsestream]
	RemoteStreamFileCommand(client: WshClient, data: CommandRemoteStreamFileData, opts?: RpcOpts): AsyncGenerator<FileData, void, boolean> {
        return client.wshRpcStream("remotestreamfile", data, opts);
    }

    // command "remotetarstream" [responsestream]
	RemoteTarStreamCommand(client: WshClient, data: CommandRemoteStreamTarData, opts?: RpcOpts): AsyncGenerator<Packet, void, boolean> {
        return client.wshRpcStream("remotetarstream", data, opts);
    }

    // command "remotewritefile" [call]
    RemoteWriteFileCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("remotewritefile", data, opts);
    }

    // command "renameappfile" [call]
    RenameAppFileCommand(client: WshClient, data: CommandRenameAppFileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("renameappfile", data, opts);
    }

    // command "resolveids" [call]
    ResolveIdsCommand(client: WshClient, data: CommandResolveIdsData, opts?: RpcOpts): Promise<CommandResolveIdsRtnData> {
        return client.wshRpcCall("resolveids", data, opts);
    }

    // command "restartbuilderandwait" [call]
    RestartBuilderAndWaitCommand(client: WshClient, data: CommandRestartBuilderAndWaitData, opts?: RpcOpts): Promise<RestartBuilderAndWaitResult> {
        return client.wshRpcCall("restartbuilderandwait", data, opts);
    }

    // command "routeannounce" [call]
    RouteAnnounceCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("routeannounce", null, opts);
    }

    // command "routeunannounce" [call]
    RouteUnannounceCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("routeunannounce", null, opts);
    }

    // command "sendtelemetry" [call]
    SendTelemetryCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("sendtelemetry", null, opts);
    }

    // command "sessionmcpgenerate" [call]
    SessionMCPGenerateCommand(client: WshClient, data: CommandSessionMCPGenerateData, opts?: RpcOpts): Promise<SessionMCPConfigData> {
        return client.wshRpcCall("sessionmcpgenerate", data, opts);
    }

    // command "sessionmcpgetavailable" [call]
    SessionMCPGetAvailableCommand(client: WshClient, opts?: RpcOpts): Promise<MCPServerInfoData[]> {
        return client.wshRpcCall("sessionmcpgetavailable", null, opts);
    }

    // command "sessionmcpresolve" [call]
    SessionMCPResolveCommand(client: WshClient, data: CommandSessionMCPResolveData, opts?: RpcOpts): Promise<ResolvedEndpointData> {
        return client.wshRpcCall("sessionmcpresolve", data, opts);
    }

    // command "sessionmcpupdatetohub" [call]
    SessionMCPUpdateToHubCommand(client: WshClient, data: CommandSessionMCPPathData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("sessionmcpupdatetohub", data, opts);
    }

    // command "sessionmcpupdatetolocal" [call]
    SessionMCPUpdateToLocalCommand(client: WshClient, data: CommandSessionMCPPathData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("sessionmcpupdatetolocal", data, opts);
    }

    // command "setconfig" [call]
    SetConfigCommand(client: WshClient, data: SettingsType, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("setconfig", data, opts);
    }

    // command "setconnectionsconfig" [call]
    SetConnectionsConfigCommand(client: WshClient, data: ConnConfigRequest, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("setconnectionsconfig", data, opts);
    }

    // command "setmeta" [call]
    SetMetaCommand(client: WshClient, data: CommandSetMetaData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("setmeta", data, opts);
    }

    // command "setpeerinfo" [call]
    SetPeerInfoCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("setpeerinfo", data, opts);
    }

    // command "setrtinfo" [call]
    SetRTInfoCommand(client: WshClient, data: CommandSetRTInfoData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("setrtinfo", data, opts);
    }

    // command "setsecrets" [call]
    SetSecretsCommand(client: WshClient, data: {[key: string]: string}, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("setsecrets", data, opts);
    }

    // command "setvar" [call]
    SetVarCommand(client: WshClient, data: CommandVarData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("setvar", data, opts);
    }

    // command "skillgetcategories" [call]
    SkillGetCategoriesCommand(client: WshClient, opts?: RpcOpts): Promise<SkillCategoryData[]> {
        return client.wshRpcCall("skillgetcategories", null, opts);
    }

    // command "skillinstall" [call]
    SkillInstallCommand(client: WshClient, data: CommandSkillInstallData, opts?: RpcOpts): Promise<InstalledSkillData> {
        return client.wshRpcCall("skillinstall", data, opts);
    }

    // command "skilllistavailable" [call]
    SkillListAvailableCommand(client: WshClient, opts?: RpcOpts): Promise<SkillData[]> {
        return client.wshRpcCall("skilllistavailable", null, opts);
    }

    // command "skilllistinstalled" [call]
    SkillListInstalledCommand(client: WshClient, data: CommandSkillListData, opts?: RpcOpts): Promise<InstalledSkillData[]> {
        return client.wshRpcCall("skilllistinstalled", data, opts);
    }

    // command "skillsearch" [call]
    SkillSearchCommand(client: WshClient, data: CommandSkillSearchData, opts?: RpcOpts): Promise<SkillData[]> {
        return client.wshRpcCall("skillsearch", data, opts);
    }

    // command "skilluninstall" [call]
    SkillUninstallCommand(client: WshClient, data: CommandSkillUninstallData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("skilluninstall", data, opts);
    }

    // command "startbuilder" [call]
    StartBuilderCommand(client: WshClient, data: CommandStartBuilderData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("startbuilder", data, opts);
    }

    // command "stopbuilder" [call]
    StopBuilderCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("stopbuilder", data, opts);
    }

    // command "streamcpudata" [responsestream]
	StreamCpuDataCommand(client: WshClient, data: CpuDataRequest, opts?: RpcOpts): AsyncGenerator<TimeSeriesData, void, boolean> {
        return client.wshRpcStream("streamcpudata", data, opts);
    }

    // command "streamdata" [call]
    StreamDataCommand(client: WshClient, data: CommandStreamData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("streamdata", data, opts);
    }

    // command "streamdataack" [call]
    StreamDataAckCommand(client: WshClient, data: CommandStreamAckData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("streamdataack", data, opts);
    }

    // command "streamtest" [responsestream]
	StreamTestCommand(client: WshClient, opts?: RpcOpts): AsyncGenerator<number, void, boolean> {
        return client.wshRpcStream("streamtest", null, opts);
    }

    // command "streamwaveai" [responsestream]
	StreamWaveAiCommand(client: WshClient, data: WaveAIStreamRequest, opts?: RpcOpts): AsyncGenerator<WaveAIPacketType, void, boolean> {
        return client.wshRpcStream("streamwaveai", data, opts);
    }

    // command "termgetscrollbacklines" [call]
    TermGetScrollbackLinesCommand(client: WshClient, data: CommandTermGetScrollbackLinesData, opts?: RpcOpts): Promise<CommandTermGetScrollbackLinesRtnData> {
        return client.wshRpcCall("termgetscrollbacklines", data, opts);
    }

    // command "test" [call]
    TestCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("test", data, opts);
    }

    // command "testaiconnection" [call]
    TestAIConnectionCommand(client: WshClient, data: CommandTestAIConnectionData, opts?: RpcOpts): Promise<CommandTestAIConnectionRtnData> {
        return client.wshRpcCall("testaiconnection", data, opts);
    }

    // command "tiltaddmcpserver" [call]
    TiltAddMCPServerCommand(client: WshClient, data: CommandTiltAddMCPServerData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltaddmcpserver", data, opts);
    }

    // command "tiltgetenvrequirements" [call]
    TiltGetEnvRequirementsCommand(client: WshClient, opts?: RpcOpts): Promise<TiltEnvRequirementData[]> {
        return client.wshRpcCall("tiltgetenvrequirements", null, opts);
    }

    // command "tiltgetenvvars" [call]
    TiltGetEnvVarsCommand(client: WshClient, opts?: RpcOpts): Promise<TiltEnvVarsData> {
        return client.wshRpcCall("tiltgetenvvars", null, opts);
    }

    // command "tiltgetlogs" [call]
    TiltGetLogsCommand(client: WshClient, data: CommandTiltGetLogsData, opts?: RpcOpts): Promise<string[]> {
        return client.wshRpcCall("tiltgetlogs", data, opts);
    }

    // command "tiltgetmcpserver" [call]
    TiltGetMCPServerCommand(client: WshClient, data: CommandTiltGetMCPServerData, opts?: RpcOpts): Promise<TiltMCPServerConfigData> {
        return client.wshRpcCall("tiltgetmcpserver", data, opts);
    }

    // command "tiltinitworkspace" [call]
    TiltInitWorkspaceCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltinitworkspace", null, opts);
    }

    // command "tiltlistmcpservers" [call]
    TiltListMCPServersCommand(client: WshClient, opts?: RpcOpts): Promise<{[key: string]: TiltMCPServerConfigData}> {
        return client.wshRpcCall("tiltlistmcpservers", null, opts);
    }

    // command "tiltremovemcpserver" [call]
    TiltRemoveMCPServerCommand(client: WshClient, data: CommandTiltRemoveMCPServerData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltremovemcpserver", data, opts);
    }

    // command "tiltrestart" [call]
    TiltRestartCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltrestart", null, opts);
    }

    // command "tiltsetenvvar" [call]
    TiltSetEnvVarCommand(client: WshClient, data: CommandTiltSetEnvVarData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltsetenvvar", data, opts);
    }

    // command "tiltsetenvvarfromsecret" [call]
    TiltSetEnvVarFromSecretCommand(client: WshClient, data: CommandTiltSetEnvVarFromSecretData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltsetenvvarfromsecret", data, opts);
    }

    // command "tiltstart" [call]
    TiltStartCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltstart", null, opts);
    }

    // command "tiltstatus" [call]
    TiltStatusCommand(client: WshClient, opts?: RpcOpts): Promise<TiltHubStatusData> {
        return client.wshRpcCall("tiltstatus", null, opts);
    }

    // command "tiltstop" [call]
    TiltStopCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltstop", null, opts);
    }

    // command "tilttogglemcp" [call]
    TiltToggleMCPCommand(client: WshClient, data: CommandTiltToggleMCPData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tilttogglemcp", data, opts);
    }

    // command "tiltupdatemcpserver" [call]
    TiltUpdateMCPServerCommand(client: WshClient, data: CommandTiltUpdateMCPServerData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("tiltupdatemcpserver", data, opts);
    }

    // command "vdomasyncinitiation" [call]
    VDomAsyncInitiationCommand(client: WshClient, data: VDomAsyncInitiationRequest, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("vdomasyncinitiation", data, opts);
    }

    // command "vdomcreatecontext" [call]
    VDomCreateContextCommand(client: WshClient, data: VDomCreateContext, opts?: RpcOpts): Promise<ORef> {
        return client.wshRpcCall("vdomcreatecontext", data, opts);
    }

    // command "vdomrender" [responsestream]
	VDomRenderCommand(client: WshClient, data: VDomFrontendUpdate, opts?: RpcOpts): AsyncGenerator<VDomBackendUpdate, void, boolean> {
        return client.wshRpcStream("vdomrender", data, opts);
    }

    // command "vdomurlrequest" [responsestream]
	VDomUrlRequestCommand(client: WshClient, data: VDomUrlRequestData, opts?: RpcOpts): AsyncGenerator<VDomUrlRequestResponse, void, boolean> {
        return client.wshRpcStream("vdomurlrequest", data, opts);
    }

    // command "waitforroute" [call]
    WaitForRouteCommand(client: WshClient, data: CommandWaitForRouteData, opts?: RpcOpts): Promise<boolean> {
        return client.wshRpcCall("waitforroute", data, opts);
    }

    // command "waveaiaddcontext" [call]
    WaveAIAddContextCommand(client: WshClient, data: CommandWaveAIAddContextData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("waveaiaddcontext", data, opts);
    }

    // command "waveaienabletelemetry" [call]
    WaveAIEnableTelemetryCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("waveaienabletelemetry", null, opts);
    }

    // command "waveaigettooldiff" [call]
    WaveAIGetToolDiffCommand(client: WshClient, data: CommandWaveAIGetToolDiffData, opts?: RpcOpts): Promise<CommandWaveAIGetToolDiffRtnData> {
        return client.wshRpcCall("waveaigettooldiff", data, opts);
    }

    // command "waveaitoolapprove" [call]
    WaveAIToolApproveCommand(client: WshClient, data: CommandWaveAIToolApproveData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("waveaitoolapprove", data, opts);
    }

    // command "waveinfo" [call]
    WaveInfoCommand(client: WshClient, opts?: RpcOpts): Promise<WaveInfoData> {
        return client.wshRpcCall("waveinfo", null, opts);
    }

    // command "webselector" [call]
    WebSelectorCommand(client: WshClient, data: CommandWebSelectorData, opts?: RpcOpts): Promise<string[]> {
        return client.wshRpcCall("webselector", data, opts);
    }

    // command "websessioncreate" [call]
    WebSessionCreateCommand(client: WshClient, data: CommandWebSessionCreateData, opts?: RpcOpts): Promise<WebSessionData> {
        return client.wshRpcCall("websessioncreate", data, opts);
    }

    // command "websessiondelete" [call]
    WebSessionDeleteCommand(client: WshClient, data: CommandWebSessionDeleteData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("websessiondelete", data, opts);
    }

    // command "websessionlist" [call]
    WebSessionListCommand(client: WshClient, data: CommandWebSessionListData, opts?: RpcOpts): Promise<WebSessionData[]> {
        return client.wshRpcCall("websessionlist", data, opts);
    }

    // command "websessionupdate" [call]
    WebSessionUpdateCommand(client: WshClient, data: CommandWebSessionUpdateData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("websessionupdate", data, opts);
    }

    // command "workspacelist" [call]
    WorkspaceListCommand(client: WshClient, opts?: RpcOpts): Promise<WorkspaceInfoData[]> {
        return client.wshRpcCall("workspacelist", null, opts);
    }

    // command "workspacemcpget" [call]
    WorkspaceMCPGetCommand(client: WshClient, data: CommandWorkspaceMCPGetData, opts?: RpcOpts): Promise<WorkspaceMCPServersData> {
        return client.wshRpcCall("workspacemcpget", data, opts);
    }

    // command "workspacemcpset" [call]
    WorkspaceMCPSetCommand(client: WshClient, data: CommandWorkspaceMCPSetData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("workspacemcpset", data, opts);
    }

    // command "workspacemcptoggle" [call]
    WorkspaceMCPToggleCommand(client: WshClient, data: CommandWorkspaceMCPToggleData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("workspacemcptoggle", data, opts);
    }

    // command "worktreearchive" [call]
    WorktreeArchiveCommand(client: WshClient, data: CommandWorktreeArchiveData, opts?: RpcOpts): Promise<ArchivedSessionData> {
        return client.wshRpcCall("worktreearchive", data, opts);
    }

    // command "worktreearchivedelete" [call]
    WorktreeArchiveDeleteCommand(client: WshClient, data: CommandWorktreeArchiveDeleteData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("worktreearchivedelete", data, opts);
    }

    // command "worktreearchivelist" [call]
    WorktreeArchiveListCommand(client: WshClient, data: CommandWorktreeArchiveListData, opts?: RpcOpts): Promise<ArchivedSessionData[]> {
        return client.wshRpcCall("worktreearchivelist", data, opts);
    }

    // command "worktreecreate" [call]
    WorktreeCreateCommand(client: WshClient, data: CommandWorktreeCreateData, opts?: RpcOpts): Promise<WorktreeInfoData> {
        return client.wshRpcCall("worktreecreate", data, opts);
    }

    // command "worktreedelete" [call]
    WorktreeDeleteCommand(client: WshClient, data: CommandWorktreeDeleteData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("worktreedelete", data, opts);
    }

    // command "worktreelist" [call]
    WorktreeListCommand(client: WshClient, data: CommandWorktreeListData, opts?: RpcOpts): Promise<WorktreeInfoData[]> {
        return client.wshRpcCall("worktreelist", data, opts);
    }

    // command "worktreemerge" [call]
    WorktreeMergeCommand(client: WshClient, data: CommandWorktreeMergeData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("worktreemerge", data, opts);
    }

    // command "worktreerename" [call]
    WorktreeRenameCommand(client: WshClient, data: CommandWorktreeRenameData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("worktreerename", data, opts);
    }

    // command "worktreerestore" [call]
    WorktreeRestoreCommand(client: WshClient, data: CommandWorktreeRestoreData, opts?: RpcOpts): Promise<WorktreeInfoData> {
        return client.wshRpcCall("worktreerestore", data, opts);
    }

    // command "worktreestatus" [call]
    WorktreeStatusCommand(client: WshClient, data: CommandWorktreeStatusData, opts?: RpcOpts): Promise<WorktreeStatusData> {
        return client.wshRpcCall("worktreestatus", data, opts);
    }

    // command "worktreesync" [call]
    WorktreeSyncCommand(client: WshClient, data: CommandWorktreeSyncData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("worktreesync", data, opts);
    }

    // command "writeappfile" [call]
    WriteAppFileCommand(client: WshClient, data: CommandWriteAppFileData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("writeappfile", data, opts);
    }

    // command "writeappgofile" [call]
    WriteAppGoFileCommand(client: WshClient, data: CommandWriteAppGoFileData, opts?: RpcOpts): Promise<CommandWriteAppGoFileRtnData> {
        return client.wshRpcCall("writeappgofile", data, opts);
    }

    // command "writeappsecretbindings" [call]
    WriteAppSecretBindingsCommand(client: WshClient, data: CommandWriteAppSecretBindingsData, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("writeappsecretbindings", data, opts);
    }

    // command "writetempfile" [call]
    WriteTempFileCommand(client: WshClient, data: CommandWriteTempFileData, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("writetempfile", data, opts);
    }

    // command "wshactivity" [call]
    WshActivityCommand(client: WshClient, data: {[key: string]: number}, opts?: RpcOpts): Promise<void> {
        return client.wshRpcCall("wshactivity", data, opts);
    }

    // command "wsldefaultdistro" [call]
    WslDefaultDistroCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        return client.wshRpcCall("wsldefaultdistro", null, opts);
    }

    // command "wsllist" [call]
    WslListCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        return client.wshRpcCall("wsllist", null, opts);
    }

    // command "wslstatus" [call]
    WslStatusCommand(client: WshClient, opts?: RpcOpts): Promise<ConnStatus[]> {
        return client.wshRpcCall("wslstatus", null, opts);
    }

}

export const RpcApi = new RpcApiType();
